# model
model: models.TemporalUnetImage
diffusion: models.GaussianDiffusionImage
horizon: 32
n_diffusion_steps: 20
action_weight: 10
loss_weights: null
loss_discount: 1
predict_epsilon: false
dim_mults: [1, 2, 4, 8]
attention: false
renderer: utils.EmptyRenderer
image_encoder_config: 
  _target_: diffuser.models.image_modules.AutoEncoder
  hidden_dim: 256
image_encoder_loss_weight: 1.0
diffusion_loss_not_to_encoder: false

# dataset
dataset_type: libero
loader: datasets.LiberoDataset
normalizer: GaussianNormalizer
preprocess_fns: []
clip_denoised: false
use_padding: true
max_path_length: 1000
task_order_index: 0
n_tasks: 22
dataset_folder: /home/tiger/myplan/libero/datasets
obs_modality:
  rgb: [agentview_rgb, eye_in_hand_rgb]
  depth: []
  low_dim: [gripper_states, joint_states]
task_embedding_format: bert
data_max_word_len: 25
task_embedding_one_hot_offset: null
max_n_episodes: null
termination_penalty: null
image_encoder: dinov2_vits14
freeze_image_encoder: true

# serialization
# logbase: ${logbase}
# prefix: diffusion/defaults
# exp_name: ${exp_name}

# training
n_epochs: 6400
loss_type: l2
batch_size: 128
train_dataset_workers: 8
learning_rate: 0.0002
ema_decay: 0.995
save_freq: 5000
sample_freq: 5000
n_saves: 5
save_parallel: false
n_reference: 8
## lr_scheduler
lr_scheduler: cosine
num_warmup_steps: 1000
bucket: null
device: cuda
seed: 0
wandb:
  project: plan-hxs
  name: diffuser-origin-libero
eval_config:
  n_eval: 10
  save_sim_states: false
  use_mp: false
  img_h: 128
  img_w: 128
  num_procs: 10
  max_steps: 600
  bddl_root_folder: "/home/tiger/myplan/libero/LIBERO/libero/libero/bddl_files"
  init_files_folder: "/home/tiger/myplan/libero/LIBERO/libero/libero/init_files"
  to_eval: true
  batch_size: 4
  num_workers: 2
  modality:
      rgb: ["agentview_rgb", "eye_in_hand_rgb"]
      depth: []
      low_dim: ["gripper_states", "joint_states"]
  obs_key_mapping:
    agentview_rgb: agentview_image
    eye_in_hand_rgb: robot0_eye_in_hand_image
    gripper_states: robot0_gripper_qpos
    joint_states: robot0_joint_pos
  query_freq: 4